In [1]:
import pandas as pd

df = pd.read_csv("Global Renewable Energy and Indicators.csv")
df.head()

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,USA,2011,Solar,85404.690027,5549.794323,5.604125e+09,1064007213,1.775278e+14,369654.644184,93087.198199,...,49.216800,57.678605,76.803228,851,75,6361,511658,25.907895,1,0
1,Australia,2008,Geothermal,22205.069382,43211.593798,6.361886e+08,1033255852,6.435372e+13,771781.636293,1752.536054,...,79.990942,1.761579,48.697825,590,39,9752,974948,95.003547,0,1
2,Canada,2013,Biomass,94102.732038,6139.117212,6.158680e+09,14895124,1.567926e+14,342707.152899,65146.592498,...,94.374040,77.657334,67.334813,101,7,311,326318,67.354539,1,0
3,Japan,2010,Biomass,88771.932910,40323.639260,8.526116e+09,1448827283,1.350464e+14,498839.574253,50257.591014,...,65.143472,44.987734,4.544289,327,3,7708,506078,33.754104,0,0
4,China,2018,Solar,93288.408581,30755.403056,5.086237e+09,1499494307,8.677956e+13,819064.362785,63101.395562,...,86.213626,62.535223,10.287199,985,69,4919,187964,59.509228,1,0

In [8]:
# Loading the dataset

df = pd.read_csv("Global Renewable Energy and Indicators.csv")

In [9]:
# Displaying first five rows

df.head()

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
0,USA,2011,Solar,85404.690027,5549.794323,5.604125e+09,1064007213,1.775278e+14,369654.644184,93087.198199,...,49.216800,57.678605,76.803228,851,75,6361,511658,25.907895,1,0
1,Australia,2008,Geothermal,22205.069382,43211.593798,6.361886e+08,1033255852,6.435372e+13,771781.636293,1752.536054,...,79.990942,1.761579,48.697825,590,39,9752,974948,95.003547,0,1
2,Canada,2013,Biomass,94102.732038,6139.117212,6.158680e+09,14895124,1.567926e+14,342707.152899,65146.592498,...,94.374040,77.657334,67.334813,101,7,311,326318,67.354539,1,0
3,Japan,2010,Biomass,88771.932910,40323.639260,8.526116e+09,1448827283,1.350464e+14,498839.574253,50257.591014,...,65.143472,44.987734,4.544289,327,3,7708,506078,33.754104,0,0
4,China,2018,Solar,93288.408581,30755.403056,5.086237e+09,1499494307,8.677956e+13,819064.362785,63101.395562,...,86.213626,62.535223,10.287199,985,69,4919,187964,59.509228,1,0

In [10]:
# Checking rows and columns

df.shape

(2500, 56)

Dataset Shape

The dataset contains 2500 rows and 56 columns. It includes information about renewable energy production, environmental factors, economic indicators, and sustainability across different countries. Since it has a good number of records and features, it is suitable for data analysis.

In [11]:
# Displaying all column names

df.columns

Index(['Country', 'Year', 'Energy Type', 'Production (GWh)',
       'Installed Capacity (MW)', 'Investments (USD)', 'Population', 'GDP',
       'Energy Consumption', 'Energy Exports', 'Energy Imports',
       'CO2 Emissions', 'Renewable Energy Jobs', 'Government Policies',
       'R&D Expenditure', 'Renewable Energy Targets',
       'Average Annual Temperature', 'Annual Rainfall', 'Solar Irradiance',
       'Wind Speed', 'Hydro Potential', 'Geothermal Potential',
       'Biomass Availability', 'Energy Storage Capacity',
       'Grid Integration Capability', 'Electricity Prices', 'Energy Subsidies',
       'International Aid for Renewables', 'Public Awareness',
       'Energy Efficiency Programs', 'Urbanization Rate',
       'Industrialization Rate', 'Energy Market Liberalization',
       'Renewable Energy Patents', 'Educational Level',
       'Technology Transfer Agreements', 'Renewable Energy Education Programs',
       'Local Manufacturing Capacity', 'Import Tariffs on Energy Equipment',
       'Export Incentives for Energy Equipment', 'Natural Disasters',
       'Political Stability', 'Corruption Perception Index',
       'Regulatory Quality', 'Rule of Law', 'Control of Corruption',
       'Economic Freedom Index', 'Ease of Doing Business', 'Innovation Index',
       'Number of Research Institutions',
       'Number of Renewable Energy Conferences',
       'Number of Renewable Energy Publications', 'Energy Sector Workforce',
       'Proportion of Energy from Renewables',
       'Public-Private Partnerships in Energy',
       'Regional Renewable Energy Cooperation'],
      dtype='object')



This step helps me understand what information is available in the dataset. Looking at the column names makes it easier to decide which features can be used for analysis, visualization, and feature engineering.

In [12]:
# Displaying dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 56 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  2500 non-null   object
 1   Year                                     2500 non-null   int64
 2   Energy Type                              2500 non-null   object
 3   Production (GWh)                         2500 non-null   float64
 4   Installed Capacity (MW)                  2500 non-null   float64
 5   Investments (USD)                        2500 non-null   float64
 6   Population                               2500 non-null   int64
 7   GDP                                      2500 non-null   float64
 8   Energy Consumption                       2500 non-null   float64
 9   Energy Exports                           2500 non-null   float64
 10  Energy Imports                           2500 non-null   float64
 11  CO2 Emissions                            2500 non-null   float64
 12  Renewable Energy Jobs                    2500 non-null   int64
 13  Government Policies                      2500 non-null   int64
 14  R&D Expenditure                          2500 non-null   float64
 15  Renewable Energy Targets                 2500 non-null   int64
 16  Average Annual Temperature               2500 non-null   float64
 17  Annual Rainfall                          2500 non-null   float64
 18  Solar Irradiance                         2500 non-null   float64
 19  Wind Speed                               2500 non-null   float64
 20  Hydro Potential                          2500 non-null   float64
 21  Geothermal Potential                     2500 non-null   float64
 22  Biomass Availability                     2500 non-null   float64
 23  Energy Storage Capacity                  2500 non-null   float64
 24  Grid Integration Capability              2500 non-null   float64
 25  Electricity Prices                       2500 non-null   float64
 26  Energy Subsidies                         2500 non-null   float64
 27  International Aid for Renewables         2500 non-null   float64
 28  Public Awareness                         2500 non-null   float64
 29  Energy Efficiency Programs               2500 non-null   int64
 30  Urbanization Rate                        2500 non-null   float64
 31  Industrialization Rate                   2500 non-null   float64
 32  Energy Market Liberalization             2500 non-null   int64
 33  Renewable Energy Patents                 2500 non-null   int64
 34  Educational Level                        2500 non-null   float64
 35  Technology Transfer Agreements           2500 non-null   int64
 36  Renewable Energy Education Programs      2500 non-null   int64
 37  Local Manufacturing Capacity             2500 non-null   float64
 38  Import Tariffs on Energy Equipment       2500 non-null   float64
 39  Export Incentives for Energy Equipment   2500 non-null   float64
 40  Natural Disasters                        2500 non-null   int64
 41  Political Stability                      2500 non-null   float64
 42  Corruption Perception Index              2500 non-null   float64
 43  Regulatory Quality                       2500 non-null   float64
 44  Rule of Law                              2500 non-null   float64
 45  Control of Corruption                    2500 non-null   float64
 46  Economic Freedom Index                   2500 non-null   float64
 47  Ease of Doing Business                   2500 non-null   float64
 48  Innovation Index                         2500 non-null   float64
 49  Number of Research Institutions          2500 non-null   int64
 50  Number of Renewable Energy Conferences   2500 non-null   int64
 51  Number of Renewable Energy Publications  2500 non-null   int64
 52  Energy Sector Workforce                  2500 non-null   int64
 53  Proportion of Energy from Renewables     2500 non-null   float64
 54  Public-Private Partnerships in Energy    2500 non-null   int64
 55  Regional Renewable Energy Cooperation    2500 non-null   int64
dtypes: float64(37), int64(17), object(2)
memory usage: 1.1+ MB

From the dataset information, I found that there are 56 columns with both numerical and categorical data. The dataset includes details such as country, energy type, production, investments, GDP, CO₂ emissions, and several environmental indicators. This gives a clear idea of the type of data available for analysis.

In [13]:
# Summary statistics of numerical columns

df.describe()

,Year,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,Energy Imports,CO2 Emissions,...,Economic Freedom Index,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation
count,2500.000000,2500.000000,2500.000000,2.500000e+03,2.500000e+03,2.500000e+03,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.00000,2500.000000,2500.000000,2500.000000,2500.000000
mean,2011.437600,48743.195073,24882.910674,4.956155e+09,7.458927e+08,1.010745e+14,495701.245158,50143.392627,50800.373871,491218.412643,...,50.736720,48.442085,50.280019,496.660400,50.431200,4978.93360,502040.891200,49.749110,0.512000,0.473600
std,6.895471,28340.915147,14463.459958,2.894789e+09,4.373146e+08,5.782363e+13,291419.017957,28833.333066,28740.851763,289783.733338,...,28.623766,28.798216,28.719483,296.181011,28.877168,2881.93256,293084.636148,28.924307,0.499956,0.499402
min,2000.000000,1053.354158,114.531639,5.886994e+06,1.255357e+06,5.603965e+10,1264.851083,1036.618008,1057.783513,1124.768458,...,0.104915,0.025281,0.025733,0.000000,0.000000,3.00000,494.000000,0.033829,0.000000,0.000000
25%,2006.000000,24309.656479,12282.213159,2.473145e+09,3.720811e+08,5.049265e+13,237300.546551,25146.745295,26347.461047,242894.720511,...,26.241437,23.519814,25.934406,234.000000,26.000000,2532.00000,244438.000000,23.968451,0.000000,0.000000
50%,2011.000000,47367.117600,24689.162460,4.961772e+09,7.515190e+08,1.027006e+14,496118.165272,49706.656938,50698.800022,475721.007886,...,50.850766,48.127673,51.398964,493.000000,51.000000,4992.50000,499151.000000,50.232069,1.000000,0.000000
75%,2017.250000,73079.452832,37438.443570,7.418384e+09,1.118019e+09,1.519604e+14,753779.282813,75567.191515,75807.642495,747649.446362,...,74.908485,73.324825,74.724073,755.000000,76.000000,7465.00000,765088.000000,74.354781,1.000000,1.000000
max,2023.000000,99937.503719,49997.387577,9.998292e+09,1.499494e+09,1.999223e+14,999618.512172,99952.509817,99912.213813,999816.500175,...,99.970526,99.901347,99.998838,999.000000,99.000000,9999.00000,999226.000000,99.988355,1.000000,1.000000

The statistical summary gives an overview of the numerical data. It shows values like the average, minimum, maximum, and standard deviation, which help me understand the distribution of different features before moving further.

In [14]:
# Checking for missing values

df.isnull().sum()

Country                                    0
Year                                       0
Energy Type                                0
Production (GWh)                           0
Installed Capacity (MW)                    0
Investments (USD)                          0
Population                                 0
GDP                                        0
Energy Consumption                         0
Energy Exports                             0
Energy Imports                             0
CO2 Emissions                              0
Renewable Energy Jobs                      0
Government Policies                        0
R&D Expenditure                            0
Renewable Energy Targets                   0
Average Annual Temperature                 0
Annual Rainfall                            0
Solar Irradiance                           0
Wind Speed                                 0
Hydro Potential                            0
Geothermal Potential                       0
Biomass Availability                       0
Energy Storage Capacity                    0
Grid Integration Capability                0
Electricity Prices                         0
Energy Subsidies                           0
International Aid for Renewables           0
Public Awareness                           0
Energy Efficiency Programs                 0
Urbanization Rate                          0
Industrialization Rate                     0
Energy Market Liberalization               0
Renewable Energy Patents                   0
Educational Level                          0
Technology Transfer Agreements             0
Renewable Energy Education Programs        0
Local Manufacturing Capacity               0
Import Tariffs on Energy Equipment         0
Export Incentives for Energy Equipment     0
Natural Disasters                          0
Political Stability                        0
Corruption Perception Index                0
Regulatory Quality                         0
Rule of Law                                0
Control of Corruption                      0
Economic Freedom Index                     0
Ease of Doing Business                     0
Innovation Index                           0
Number of Research Institutions            0
Number of Renewable Energy Conferences     0
Number of Renewable Energy Publications    0
Energy Sector Workforce                    0
Proportion of Energy from Renewables       0
Public-Private Partnerships in Energy      0
Regional Renewable Energy Cooperation      0
dtype: int64

I checked the dataset for missing values to make sure the data is complete before starting the analysis. After checking, I found that there are no missing values in the dataset, so no additional cleaning was required.

In [15]:
# Filling missing values if any are present

for col in df.select_dtypes(include='number').columns:
    df[col] = df[col].fillna(df[col].median())

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

Even though my dataset does not contain missing values, I included this step because it is a common part of the data preprocessing process. If any missing values were present, I would replace numerical values with the median because it is less affected by extreme values. For categorical columns, I would use the mode, as it replaces missing values with the most frequently occurring category.

In [16]:
# Checking for duplicate rows

df.duplicated().sum()

np.int64(0)

In [17]:
df = df.drop_duplicates()

I checked whether the dataset contained duplicate records. Removing duplicate data helps improve the quality of analysis and prevents repeated information from affecting the results.

General Analysis

After exploring the dataset, I noticed that it contains information about renewable energy from different countries over multiple years. It includes details about energy production, installed capacity, investments, GDP, CO₂ emissions, weather conditions, and other sustainability-related factors. Since the dataset combines environmental and economic information, it can be used to understand how different factors influence renewable energy production.

Relationship Between Features
Country identifies where the data belongs.
Year helps compare changes over time.
Energy Type shows the renewable energy source, such as solar, wind, or hydro.
Installed Capacity and Production are closely related because a higher installed capacity usually results in greater energy production.
Investments can influence the growth of renewable energy projects.
GDP may affect a country's ability to invest in renewable energy.
CO₂ Emissions can be compared with renewable energy production to understand environmental impact.
Population influences the overall demand for energy.

These relationships help in understanding how different factors work together in the renewable energy sector.

In [18]:
# Creating a new feature to measure production efficiency

df["Production per MW"] = df["Production (GWh)"] / df["Installed Capacity (MW)"]

df.head()

,Country,Year,Energy Type,Production (GWh),Installed Capacity (MW),Investments (USD),Population,GDP,Energy Consumption,Energy Exports,...,Ease of Doing Business,Innovation Index,Number of Research Institutions,Number of Renewable Energy Conferences,Number of Renewable Energy Publications,Energy Sector Workforce,Proportion of Energy from Renewables,Public-Private Partnerships in Energy,Regional Renewable Energy Cooperation,Production per MW
0,USA,2011,Solar,85404.690027,5549.794323,5.604125e+09,1064007213,1.775278e+14,369654.644184,93087.198199,...,57.678605,76.803228,851,75,6361,511658,25.907895,1,0,15.388803
1,Australia,2008,Geothermal,22205.069382,43211.593798,6.361886e+08,1033255852,6.435372e+13,771781.636293,1752.536054,...,1.761579,48.697825,590,39,9752,974948,95.003547,0,1,0.513868
2,Canada,2013,Biomass,94102.732038,6139.117212,6.158680e+09,14895124,1.567926e+14,342707.152899,65146.592498,...,77.657334,67.334813,101,7,311,326318,67.354539,1,0,15.328382
3,Japan,2010,Biomass,88771.932910,40323.639260,8.526116e+09,1448827283,1.350464e+14,498839.574253,50257.591014,...,44.987734,4.544289,327,3,7708,506078,33.754104,0,0,2.201486
4,China,2018,Solar,93288.408581,30755.403056,5.086237e+09,1499494307,8.677956e+13,819064.362785,63101.395562,...,62.535223,10.287199,985,69,4919,187964,59.509228,1,0,3.033236

To gain additional insight, I created a new column called Production per MW. This feature represents how much electricity is produced for every megawatt of installed capacity. It helps compare the efficiency of renewable energy production across different records instead of looking only at the total production.